chore : fix yaml
설정 관련 값이므로 yaml에 등록한 후 환경변수로 받아오려 했으나 
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
오류가 지속적으로 발생하여 수정